apiVersion: v1
kind: Service
metadata:
  name: kubetest
  labels:
    app: kubetest
    tier: server
spec:
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: kubetest
    tier: server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubetest
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kubetest
        tier: server
    spec:
      containers:
      - name: kubetest
        image: vinhut/simple-kube-app:green
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            httpHeaders:
              - name: X-Custom-Header
                value: Test
          initialDelaySeconds: 25
          periodSeconds: 5
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kubetest
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: kubetest
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
